created: '2025-06-05'
metadata:
  author: Shreya Mukherjee
  description: A modular and reproducible framework for simulating, fitting and analyzing
    compartmental epidemic models
  package_name: epimodels 
  project_name: Epidemic Modeling Framework
  project_slug: modeling-framework
  python_version: '3.11'
  version: v0.1.0


SIR_model:
  compartments: [S, I, R]
  parameters: {beta: 0.25, gamma: 0.15, mu: 0.015}
  time varying:
    beta:
      default: 0.3
      schedule:
        - {time: 50, value: 0.1}
        - {time: 100, value: 0.4}
  transitions: {"S -> I": "beta * S * I / N", "I -> R": "gamma * I", "-> S": "mu * N", "S ->": "mu * S", "I ->": "mu * I", "R ->": "mu * R"}
  population: 1000
  initial_conditions: {S: 990, I: 10, R: 0}
  assumptions: "The population is closed (no births or deaths). The disease is transmitted through direct contact. Immunity is permanent after recovery."
  simulation_time: 160
  time_unit: days
  plot_settings:
    y_scale: linear
    scale_by_population: false
  calibration_settings:
    target_data: noisy_data.csv 
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false
    parameter_bounds:
      beta: [0.0, 5.0]
      gamma: [0.0, 2.0]
      mu: [0.0, 1.0]
    


    
SEIR_model:
 compartments: [S, E, I, R] 
 parameters: {beta: 0.3, sigma: 0.1, gamma: 0.1, mu: 0.01}
 transitions: {"S -> E": "beta * S * I / N", "E -> I": "sigma * E", "I -> R": "gamma * I", "-> S": "mu * N", "S ->": "mu * S", "E ->": "mu * E", "I ->": "mu * I", "R ->": "mu * R"}
 population: 1000
 initial_conditions: {S: 990, E: 0, I: 10, R: 0}
 assumptions: The population is closed (no births or deaths). The disease has an exposed stage before becoming infectious. Immunity is permanent after recovery.
 simulation_time: 160
 time_unit: days
 plot_settings:
    y_scale: linear
    scale_by_population: false
 calibration_settings:
    target_data: synthetic_data.csv # or file_name.csv for real data  
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false
    


SIS_model:
  compartments: [S, I]
  parameters: {beta: 0.3, gamma: 0.1, mu: 0.01}
  transitions: {"S -> I": "beta * S * I / N", "I -> S": "gamma * I", "-> S": "mu * N", "S ->": "mu * S", "I ->": "mu * I"}
  population: 1000
  initial_conditions: {S: 990, I: 10}
  assumptions: The population is closed (no births or deaths). The disease does not confer permanent immunity. After recovery, individuals return to the susceptible class (no immunity).
  tags: [standard_model]
  simulation_time: 160
  time_unit: days
  plot_settings:
    y_scale: linear
    scale_by_population: false
  calibration_settings:
    target_data: synthetic_data.csv # or file_name.csv for real data    
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false


SIS_model_test:
  compartments: [S, I]
  parameters: {beta: 0.35, gamma: 0.15, mu: 0.015}
  transitions: {"S -> I": "beta * S * I / N", "I -> S": "gamma * I", "-> S": "mu * N", "S ->": "mu * S", "I ->": "mu * I"}
  population: 1000
  initial_conditions: {S: 990, I: 10}
  assumptions: The population is closed (no births or deaths). The disease does not confer permanent immunity. After recovery, individuals return to the susceptible class (no immunity).
  simulation_time: 160
  time_unit: days
  plot_settings:
    y_scale: linear
    scale_by_population: false
  calibration_settings:
    target_data: synthetic_data.csv # or file_name.csv for real data  
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false



TB_Kuddus_2022_model:   
  compartments: [S, Ls, Is, Lr, Ir, R]
  parameters: {mu: 0.0142857, beta_s: 1.57e-8, beta_r: 6.25e-9, alpha_s: 0.129, alpha_r: 0.129, omega_s: 0.287, omega_r: 0.12, rho: 0.07, phi_s: 0.37, phi_r: 0.37, tau_s: 0.94, tau_r: 0.78, gamma: 0.1 }
  transitions: {"R -> S": "gamma * R", "Is -> S": "phi_s * Is", "Ir -> S": "phi_r * Ir", "S -> Ls": "beta_s * Is * S / N", "S -> Lr": "beta_r * Ir * S / N","S ->": "mu * S", "-> S": "mu * N", "Ls -> Is": "alpha_s * Ls", "Ls ->": "mu * Ls", "Is -> R": "omega_s * Is", "Is -> R_extra": "(1 - rho) * tau_s * Is" , "Is ->": "mu * Is", "Is -> Ir": "rho * tau_s * Is", "Lr -> Ir": "alpha_r * Lr", "Lr ->": "mu * Lr", "Ir -> R": "omega_r * Ir", "Ir -> R_extra": "tau_r * Ir", "Ir ->": "mu * Ir", "Ir -> S": "phi_r * Ir", "R ->": "mu * R"}
  population: 100000
  initial_conditions: {Ls: 400, Is: 300, Lr: 10, Ir: 400, R: 5, S: 98885}
  assumptions: TB transmission with drug-sensitive (DS) and drug-resistant (DR) strains, based on Kuddus (2022).
  tags: [Tuberculosis, drug_resistance]
  simulation_time: 15
  time_unit: years
  plot_settings:
    y_scale: linear
    scale_by_population: true   
    per_unit: 100000   
  calibration_settings:   
    target_data: TB_synthetic_data.csv # or file_name.csv for real data  
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false  
    

TB_sulayman_2021_model:   
  compartments: [S, V, E, I, R]
  parameters: {Lambda: 5, mu: 0.15, beta: 0.25, theta: 0.069, xi: 0.5, omega: 0.5, k: 0.02, tau: 2.5, delta: 0.12, sigma: 0.5, p: 0.5}
  transitions: {"-> S": "Lambda", "S -> V": "xi * S", "V -> S": "theta * V", "S -> E": "beta * S * I", "V -> E": "omega * betaa * V * I", "E -> I": "k * E + p * beta * E * I", "I -> R": "tau * I", "I ->": "(mu + delta) * I", "S ->": "mu * S", "V ->": "mu * V", "E ->": "mu * E", "I ->": "mu * I", "R ->": "mu * R", "R -> E": "sigma * beta * I * R"}
  population: 100000
  assumptions: |
    Sulayman et al. (2021) propose an SVEIRE TB model incorporating:
      - Vaccination (V) with waning immunity (θ) and imperfect efficacy (ω)
      - Exogenous reinfection (p) and reinfection among recovered (σ)
      - Natural mortality (μ) and TB-induced mortality (δ)
      - Recruitment inflow (Λ)
      - Disease progression from exposed (E) to infected (I) via rate (k)
      - Recovery of infected individuals at rate (τ)
  simulation_time: 50
  time_unit: years
  plot_settings:
    y_scale: linear
    scale_by_population: true   
    per_unit: 100000
  calibration_settings:
    target_data: TB_data.csv # or file_name.csv for real data  
    noise_std: 5.0
    subset_ratio: 0.7
    optimizers: [Nelder-Mead, BFGS, L-BFGS-B]
    update_config: false
