site_name: Generalized Compartmental Modeling Framework
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - content.code.select
    - navigation.tabs
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.escapeall
  - pymdownx.progressbar
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: index.md
  - Github Repo: https://github.com/dsih-artpark/infectious-disease-models.git
  - Presentations:
      - "Generalized Framework (2025-08-12)": presentations/generalized_framework_2025-08-12.pdf
  - Configuration:
      - YAML Format: configuration/yaml_config.md
  - Usage:
      - Workflow: usage/workflow.md
      - Simulation: usage/simulation.md
      - Noise Injection: usage/noise_injection.md
      - Parameter Fitting: usage/parameter_fitting.md
  - Features:
      - Extensibility: features/extensibility.md
      - Advanced Features: features/advanced_features.md
      - Outputs: features/outputs.md
  - Debugging:
      - Issues Encountered: debugging/issues_encountered.md
      - Improvements: debugging/improvements.md
  - Developer Guide:
      - Overview: dev/index.md
      - model.py: dev/model.md
      - calibration.py: dev/calibration.md
      - plotting.py: dev/plotting.md
  - Example Models:
      - Standard Models:
        - SIR Model: models/sir.md
        - SEIR Model: models/seir.md
        - SIS Model: models/sis.md
      - Published Models:
        - TB Model: 
          - TB_Kuddus_2022: models/TB_Kuddus_2022.md
          - TB_Ayinla_2021: models/TB_Ayinla_2021.md
  - References: references.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js