site_name: Generalized Compartmental Modeling Framework
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
nav:
  - Home: index.md
  - Presentations:
      - "Generalized Framework (2025-08-12)": presentations/generalized_framework_2025-08-12.pptx
  - Configuration:
      - YAML Format: configuration/yaml_config.md
  - Usage:
      - Workflow: usage/workflow.md
      - Simulation: usage/simulation.md
      - Noise Injection: usage/noise_injection.md
      - Parameter Fitting: usage/parameter_fitting.md
  - Features:
      - Extensibility: features/extensibility.md
      - Advanced Features: features/advanced_features.md
      - Outputs: features/outputs.md
  - Debugging:
      - Issues Encountered: debugging/issues_encountered.md
      - Improvements: debugging/improvements.md
  - References: references.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js